from typing import Protocol

from remember_hub.contracts.percepts import Detection, Dimensions


class SamBackend(Protocol):
    async def start_session(self, vocabulary: list[str]) -> None: ...
    async def push_frame(self, frame_id: str, jpeg: bytes, wh: Dimensions) -> list[Detection]: ...
    async def add_concept(self, noun: str) -> None: ...
    async def end_session(self) -> None: ...
